---
micronaut:
  application.name: DockerSpringBootMicronaut
  server:
    port: 9000
  endpoints:
    all:
      enabled: true
      sensite: true
      path: /root
    health:
      enabled: true
      sensitive: true